<a href="https://colab.research.google.com/github/briskicedteaa/rdkit-cheminformatics-notebooks-/blob/main/Molecular_Similarity_Search.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [35]:
!pip install rdkit
from rdkit import Chem
import pandas as pd
from rdkit import RDLogger

Requirement already satisfied: rdkit in /usr/local/lib/python3.12/dist-packages (2026.3.4)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from rdkit) (2.0.2)
Requirement already satisfied: Pillow in /usr/local/lib/python3.12/dist-packages (from rdkit) (11.3.0)

In [ ]:
df = pd.read_csv('/content/File.csv', sep =';' )
df = df.drop(columns=df.columns.difference(['Target ChEMBL ID', 'Smiles']))
df = df.dropna()
df

                                                  Smiles Target ChEMBL ID
0      CN1CC[C@@]2(C)c3cc(OC(=O)NCCCCCCCCCN4CCOCC4)cc...        CHEMBL220
1           Cc1ccc(C(=O)/C(=N/O)SCC[N+](C)(C)C)cc1.[Cl-]        CHEMBL220
2      NC(=O)c1cc[n+](C/C=C/C[n+]2ccc(/C=N/O)cc2)cc1....        CHEMBL220
3          O/N=C/c1cc[n+](CCC[n+]2ccccc2)cc1.[Br-].[Br-]        CHEMBL220
4      O/N=C/c1cc[n+](CCC[n+]2ccc3ccccc3c2)cc1.[Br-]....        CHEMBL220
...                                                  ...              ...
20127  CC1=CC(=O)[C@@](C)(O)C(=O)/C1=C\Nc1ccc(Cc2cccc...        CHEMBL220
20128  COc1cc2c(cc1OCCCCCC1CCSS1)C(=O)C(CC1CCN(Cc3ccc...        CHEMBL220
20129  C#CCCCOc1c(CN2CCc3ccccc3C2)cc(-c2cc(=O)c3ccccc...        CHEMBL220
20130              O=C(CCC1CCN(CC2CCCCC2)CC1)c1ccc(O)cc1        CHEMBL220
20131     COc1c(C(=O)CCC2CCN(CC3CCCCC3)CC2)cc(F)c(N)c1Br        CHEMBL220

[20045 rows x 2 columns]

In [42]:
for index, row in df.iterrows():
  target_ID = row['Target ChEMBL ID']
  smiles_string = row['Smiles']
  mol = Chem.MolFromSmiles(smiles_string)

  RDLogger.DisableLog('rdkit.Chem.Outputs')

valid_mask = [Chem.MolFromSmiles(s) is not None for s in df['Smiles']]

df = df[valid_mask]

df.to_csv('File.csv', index=False)

display(df)

,Smiles,Target ChEMBL ID,Fingerprints
0,CN1CC[C@@]2(C)c3cc(OC(=O)NCCCCCCCCCN4CCOCC4)cc...,CHEMBL220,"[1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
1,Cc1ccc(C(=O)/C(=N/O)SCC[N+](C)(C)C)cc1.[Cl-],CHEMBL220,"[1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
2,NC(=O)c1cc[n+](C/C=C/C[n+]2ccc(/C=N/O)cc2)cc1....,CHEMBL220,"[1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
3,O/N=C/c1cc[n+](CCC[n+]2ccccc2)cc1.[Br-].[Br-],CHEMBL220,"[1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
4,O/N=C/c1cc[n+](CCC[n+]2ccc3ccccc3c2)cc1.[Br-]....,CHEMBL220,"[1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
...,...,...,...
20127,CC1=CC(=O)[C@@](C)(O)C(=O)/C1=C\Nc1ccc(Cc2cccc...,CHEMBL220,"[1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
20128,COc1cc2c(cc1OCCCCCC1CCSS1)C(=O)C(CC1CCN(Cc3ccc...,CHEMBL220,"[1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
20129,C#CCCCOc1c(CN2CCc3ccccc3C2)cc(-c2cc(=O)c3ccccc...,CHEMBL220,"[1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
20130,O=C(CCC1CCN(CC2CCCCC2)CC1)c1ccc(O)cc1,CHEMBL220,"[1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
20131,COc1c(C(=O)CCC2CCN(CC3CCCCC3)CC2)cc(F)c(N)c1Br,CHEMBL220,"[1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."

In [43]:
from rdkit.Chem import rdFingerprintGenerator

mfpgen = rdFingerprintGenerator.GetMorganGenerator(radius=2, fpSize=256)

mol = Chem.MolFromSmiles(smiles_string)

fp = mfpgen.GetFingerprint(mol)
fp.ToList()[:10]
df['Fingerprints'] = fp
display(df)

,Smiles,Target ChEMBL ID,Fingerprints
0,CN1CC[C@@]2(C)c3cc(OC(=O)NCCCCCCCCCN4CCOCC4)cc...,CHEMBL220,"[1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
1,Cc1ccc(C(=O)/C(=N/O)SCC[N+](C)(C)C)cc1.[Cl-],CHEMBL220,"[1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
2,NC(=O)c1cc[n+](C/C=C/C[n+]2ccc(/C=N/O)cc2)cc1....,CHEMBL220,"[1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
3,O/N=C/c1cc[n+](CCC[n+]2ccccc2)cc1.[Br-].[Br-],CHEMBL220,"[1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
4,O/N=C/c1cc[n+](CCC[n+]2ccc3ccccc3c2)cc1.[Br-]....,CHEMBL220,"[1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
...,...,...,...
20127,CC1=CC(=O)[C@@](C)(O)C(=O)/C1=C\Nc1ccc(Cc2cccc...,CHEMBL220,"[1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
20128,COc1cc2c(cc1OCCCCCC1CCSS1)C(=O)C(CC1CCN(Cc3ccc...,CHEMBL220,"[1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
20129,C#CCCCOc1c(CN2CCc3ccccc3C2)cc(-c2cc(=O)c3ccccc...,CHEMBL220,"[1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
20130,O=C(CCC1CCN(CC2CCCCC2)CC1)c1ccc(O)cc1,CHEMBL220,"[1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
20131,COc1c(C(=O)CCC2CCN(CC3CCCCC3)CC2)cc(F)c(N)c1Br,CHEMBL220,"[1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."

In [45]:
from rdkit import DataStructs

query_mol = Chem.MolFromSmiles("CN1CCI[C@@]2(C)C3Cc(OC(=O)NCCCCCCCCCN4CCOCC4)cCC3N(C)[C@@H]12")
mfpgen = rdFingerprintGenerator.GetMorganGenerator(radius=2, fpSize=256)
query_fp = mfpgen.GetFingerprint(query_mol)

similarities = []
for index, row_data in df.iterrows():
    mol = Chem.MolFromSmiles(row_data['Smiles'])
    if mol is not None:
        fp = mfpgen.GetFingerprint(mol)
        similarity = DataStructs.TanimotoSimilarity(query_fp, fp)
        similarities.append(similarity)
    else:
        similarities.append(None)

df['similarity'] = similarities

display(df)

,Smiles,Target ChEMBL ID,Fingerprints,similarity
0,CN1CC[C@@]2(C)c3cc(OC(=O)NCCCCCCCCCN4CCOCC4)cc...,CHEMBL220,"[1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",0.537313
1,Cc1ccc(C(=O)/C(=N/O)SCC[N+](C)(C)C)cc1.[Cl-],CHEMBL220,"[1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",0.185714
2,NC(=O)c1cc[n+](C/C=C/C[n+]2ccc(/C=N/O)cc2)cc1....,CHEMBL220,"[1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",0.103896
3,O/N=C/c1cc[n+](CCC[n+]2ccccc2)cc1.[Br-].[Br-],CHEMBL220,"[1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",0.126761
4,O/N=C/c1cc[n+](CCC[n+]2ccc3ccccc3c2)cc1.[Br-]....,CHEMBL220,"[1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",0.135135
...,...,...,...,...
20127,CC1=CC(=O)[C@@](C)(O)C(=O)/C1=C\Nc1ccc(Cc2cccc...,CHEMBL220,"[1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",0.184211
20128,COc1cc2c(cc1OCCCCCC1CCSS1)C(=O)C(CC1CCN(Cc3ccc...,CHEMBL220,"[1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",0.197917
20129,C#CCCCOc1c(CN2CCc3ccccc3C2)cc(-c2cc(=O)c3ccccc...,CHEMBL220,"[1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",0.195652
20130,O=C(CCC1CCN(CC2CCCCC2)CC1)c1ccc(O)cc1,CHEMBL220,"[1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",0.205479
20131,COc1c(C(=O)CCC2CCN(CC3CCCCC3)CC2)cc(F)c(N)c1Br,CHEMBL220,"[1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",0.200000