<a href="https://colab.research.google.com/github/briskicedteaa/rdkit-cheminformatics-notebooks-/blob/main/Murcko_Scaffolds.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install rdkit
from rdkit import Chem
import pandas as pd

Collecting rdkit
  Downloading rdkit-2026.3.4-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (3.8 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from rdkit) (2.0.2)
Requirement already satisfied: Pillow in /usr/local/lib/python3.12/dist-packages (from rdkit) (11.3.0)
Downloading rdkit-2026.3.4-cp312-cp312-manylinux_2_28_x86_64.whl (37.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 37.4/37.4 MB 53.1 MB/s eta 0:00:00
Installing collected packages: rdkit
Successfully installed rdkit-2026.3.4

In [ ]:
df = pd.read_csv('/content/File.csv', sep =';' )
df = df.drop(columns=df.columns.difference(['Target ChEMBL ID', 'Smiles']))
df = df.dropna()
df

                                                  Smiles Target ChEMBL ID
0      CN1CC[C@@]2(C)c3cc(OC(=O)NCCCCCCCCCN4CCOCC4)cc...        CHEMBL220
1           Cc1ccc(C(=O)/C(=N/O)SCC[N+](C)(C)C)cc1.[Cl-]        CHEMBL220
2      NC(=O)c1cc[n+](C/C=C/C[n+]2ccc(/C=N/O)cc2)cc1....        CHEMBL220
3          O/N=C/c1cc[n+](CCC[n+]2ccccc2)cc1.[Br-].[Br-]        CHEMBL220
4      O/N=C/c1cc[n+](CCC[n+]2ccc3ccccc3c2)cc1.[Br-]....        CHEMBL220
...                                                  ...              ...
20127  CC1=CC(=O)[C@@](C)(O)C(=O)/C1=C\Nc1ccc(Cc2cccc...        CHEMBL220
20128  COc1cc2c(cc1OCCCCCC1CCSS1)C(=O)C(CC1CCN(Cc3ccc...        CHEMBL220
20129  C#CCCCOc1c(CN2CCc3ccccc3C2)cc(-c2cc(=O)c3ccccc...        CHEMBL220
20130              O=C(CCC1CCN(CC2CCCCC2)CC1)c1ccc(O)cc1        CHEMBL220
20131     COc1c(C(=O)CCC2CCN(CC3CCCCC3)CC2)cc(F)c(N)c1Br        CHEMBL220

[20045 rows x 2 columns]

In [ ]:
for index, row in df.iterrows():
  target_ID = row['Target ChEMBL ID']
  smiles_string = row['Smiles']
  mol = Chem.MolFromSmiles(smiles_string)


valid_mask = [Chem.MolFromSmiles(s) is not None for s in df['Smiles']]

df = df[valid_mask]

df.to_csv('File.csv', index=False)

display(df)

                                                  Smiles Target ChEMBL ID
0      CN1CC[C@@]2(C)c3cc(OC(=O)NCCCCCCCCCN4CCOCC4)cc...        CHEMBL220
1           Cc1ccc(C(=O)/C(=N/O)SCC[N+](C)(C)C)cc1.[Cl-]        CHEMBL220
2      NC(=O)c1cc[n+](C/C=C/C[n+]2ccc(/C=N/O)cc2)cc1....        CHEMBL220
3          O/N=C/c1cc[n+](CCC[n+]2ccccc2)cc1.[Br-].[Br-]        CHEMBL220
4      O/N=C/c1cc[n+](CCC[n+]2ccc3ccccc3c2)cc1.[Br-]....        CHEMBL220
...                                                  ...              ...
20127  CC1=CC(=O)[C@@](C)(O)C(=O)/C1=C\Nc1ccc(Cc2cccc...        CHEMBL220
20128  COc1cc2c(cc1OCCCCCC1CCSS1)C(=O)C(CC1CCN(Cc3ccc...        CHEMBL220
20129  C#CCCCOc1c(CN2CCc3ccccc3C2)cc(-c2cc(=O)c3ccccc...        CHEMBL220
20130              O=C(CCC1CCN(CC2CCCCC2)CC1)c1ccc(O)cc1        CHEMBL220
20131     COc1c(C(=O)CCC2CCN(CC3CCCCC3)CC2)cc(F)c(N)c1Br        CHEMBL220

[20045 rows x 2 columns]

In [30]:
from rdkit.Chem.Scaffolds import MurckoScaffold

csv_data = pd.read_csv("File.csv")

def extract_single_scaffold(smiles_text):
    mol = Chem.MolFromSmiles(smiles_text)
    if mol is not None:
        scaffold_obj = MurckoScaffold.GetScaffoldForMol(mol)
        return Chem.MolToSmiles(scaffold_obj)
    return None

csv_data['scaffold_results'] = csv_data['Smiles'].apply(extract_single_scaffold)

df['Murcko Scaffolds'] = df['Smiles'].apply(extract_single_scaffold)

display(df)

,Smiles,Target ChEMBL ID,Murcko Scaffolds
0,CN1CC[C@@]2(C)c3cc(OC(=O)NCCCCCCCCCN4CCOCC4)cc...,CHEMBL220,O=C(NCCCCCCCCCN1CCOCC1)Oc1ccc2c(c1)C1CCN[C@@H]1N2
1,Cc1ccc(C(=O)/C(=N/O)SCC[N+](C)(C)C)cc1.[Cl-],CHEMBL220,c1ccccc1
2,NC(=O)c1cc[n+](C/C=C/C[n+]2ccc(/C=N/O)cc2)cc1....,CHEMBL220,C(=C\C[n+]1ccccc1)/C[n+]1ccccc1
3,O/N=C/c1cc[n+](CCC[n+]2ccccc2)cc1.[Br-].[Br-],CHEMBL220,c1cc[n+](CCC[n+]2ccccc2)cc1
4,O/N=C/c1cc[n+](CCC[n+]2ccc3ccccc3c2)cc1.[Br-]....,CHEMBL220,c1cc[n+](CCC[n+]2ccc3ccccc3c2)cc1
...,...,...,...
20127,CC1=CC(=O)[C@@](C)(O)C(=O)/C1=C\Nc1ccc(Cc2cccc...,CHEMBL220,O=C1C=C/C(=C/Nc2ccc(Cc3ccccc3)cc2)C(=O)C1
20128,COc1cc2c(cc1OCCCCCC1CCSS1)C(=O)C(CC1CCN(Cc3ccc...,CHEMBL220,O=C1c2cc(OCCCCCC3CCSS3)ccc2CC1CC1CCN(Cc2ccccc2...
20129,C#CCCCOc1c(CN2CCc3ccccc3C2)cc(-c2cc(=O)c3ccccc...,CHEMBL220,O=c1cc(-c2cccc(CN3CCc4ccccc4C3)c2)oc2ccccc12
20130,O=C(CCC1CCN(CC2CCCCC2)CC1)c1ccc(O)cc1,CHEMBL220,O=C(CCC1CCN(CC2CCCCC2)CC1)c1ccccc1
20131,COc1c(C(=O)CCC2CCN(CC3CCCCC3)CC2)cc(F)c(N)c1Br,CHEMBL220,O=C(CCC1CCN(CC2CCCCC2)CC1)c1ccccc1