<a href="https://colab.research.google.com/github/briskicedteaa/rdkit-cheminformatics-notebooks-/blob/main/Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install rdkit
from rdkit import Chem
import pandas as pd

Collecting rdkit
  Downloading rdkit-2026.3.4-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (3.8 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from rdkit) (2.0.2)
Requirement already satisfied: Pillow in /usr/local/lib/python3.12/dist-packages (from rdkit) (11.3.0)
Downloading rdkit-2026.3.4-cp312-cp312-manylinux_2_28_x86_64.whl (37.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 37.4/37.4 MB 45.4 MB/s eta 0:00:00
Installing collected packages: rdkit
Successfully installed rdkit-2026.3.4

In [2]:
df = pd.read_csv('/content/File.csv', sep =';' )
df = df.drop(columns=df.columns.difference(['Target ChEMBL ID', 'Smiles']))
df = df.dropna()
df

                                                  Smiles Target ChEMBL ID
0      CN1CC[C@@]2(C)c3cc(OC(=O)NCCCCCCCCCN4CCOCC4)cc...        CHEMBL220
1           Cc1ccc(C(=O)/C(=N/O)SCC[N+](C)(C)C)cc1.[Cl-]        CHEMBL220
2      NC(=O)c1cc[n+](C/C=C/C[n+]2ccc(/C=N/O)cc2)cc1....        CHEMBL220
3          O/N=C/c1cc[n+](CCC[n+]2ccccc2)cc1.[Br-].[Br-]        CHEMBL220
4      O/N=C/c1cc[n+](CCC[n+]2ccc3ccccc3c2)cc1.[Br-]....        CHEMBL220
...                                                  ...              ...
20127  CC1=CC(=O)[C@@](C)(O)C(=O)/C1=C\Nc1ccc(Cc2cccc...        CHEMBL220
20128  COc1cc2c(cc1OCCCCCC1CCSS1)C(=O)C(CC1CCN(Cc3ccc...        CHEMBL220
20129  C#CCCCOc1c(CN2CCc3ccccc3C2)cc(-c2cc(=O)c3ccccc...        CHEMBL220
20130              O=C(CCC1CCN(CC2CCCCC2)CC1)c1ccc(O)cc1        CHEMBL220
20131     COc1c(C(=O)CCC2CCN(CC3CCCCC3)CC2)cc(F)c(N)c1Br        CHEMBL220

[20045 rows x 2 columns]

In [3]:
for index, row in df.iterrows():
  target_ID = row['Target ChEMBL ID']
  smiles_string = row['Smiles']
  mol = Chem.MolFromSmiles(smiles_string)

valid_mask = [Chem.MolFromSmiles(s) is not None for s in df['Smiles']]

df = df[valid_mask]

df.to_csv('File.csv', index=False)

display(df)

                                                  Smiles Target ChEMBL ID
0      CN1CC[C@@]2(C)c3cc(OC(=O)NCCCCCCCCCN4CCOCC4)cc...        CHEMBL220
1           Cc1ccc(C(=O)/C(=N/O)SCC[N+](C)(C)C)cc1.[Cl-]        CHEMBL220
2      NC(=O)c1cc[n+](C/C=C/C[n+]2ccc(/C=N/O)cc2)cc1....        CHEMBL220
3          O/N=C/c1cc[n+](CCC[n+]2ccccc2)cc1.[Br-].[Br-]        CHEMBL220
4      O/N=C/c1cc[n+](CCC[n+]2ccc3ccccc3c2)cc1.[Br-]....        CHEMBL220
...                                                  ...              ...
20127  CC1=CC(=O)[C@@](C)(O)C(=O)/C1=C\Nc1ccc(Cc2cccc...        CHEMBL220
20128  COc1cc2c(cc1OCCCCCC1CCSS1)C(=O)C(CC1CCN(Cc3ccc...        CHEMBL220
20129  C#CCCCOc1c(CN2CCc3ccccc3C2)cc(-c2cc(=O)c3ccccc...        CHEMBL220
20130              O=C(CCC1CCN(CC2CCCCC2)CC1)c1ccc(O)cc1        CHEMBL220
20131     COc1c(C(=O)CCC2CCN(CC3CCCCC3)CC2)cc(F)c(N)c1Br        CHEMBL220

[20045 rows x 2 columns]

In [4]:
from rdkit.Chem import Descriptors

df['NumHeavyAtoms'] = None
df['LogP'] = None
df['HBA'] = None
df['HBD'] = None
df['TPSA'] = None
df['RotatableBonds'] = None
df['NumRings'] = None
df['MolWt'] = None
df['Parsing Succesful?'] = True

for index, row in df.iterrows():
  compound_name = row['Target ChEMBL ID']
  smiles_string = row['Smiles']

  mol = Chem.MolFromSmiles(smiles_string)
  if mol:
    numheavyatoms = mol.GetNumHeavyAtoms()
    logp = Descriptors.MolLogP(mol)
    hba = Descriptors.NumHAcceptors(mol)
    hbd = Descriptors.NumHDonors(mol)
    tpsa = Descriptors.TPSA(mol)
    MolWt = Descriptors.MolWt(mol)
    rot_bonds = Descriptors.NumRotatableBonds(mol)
    numrings = mol.GetRingInfo().NumRings()

    df.loc[index, 'NumHeavyAtoms'] = numheavyatoms
    df.loc[index, 'LogP'] = logp
    df.loc[index, 'HBA'] = hba
    df.loc[index, 'HBD'] = hbd
    df.loc[index, 'TPSA'] = tpsa
    df.loc[index, 'RotatableBonds'] = rot_bonds
    df.loc[index, 'NumRings'] = numrings
    df.loc[index, 'MolWt'] = MolWt

  else:
    print(f"Compound {compound_name} (Smiles: {smiles_string}): Invalid Smiles string")
    df.loc[index, 'Parsing Succesful?'] = False

display(df)

,Smiles,Target ChEMBL ID,NumHeavyAtoms,LogP,HBA,HBD,TPSA,RotatableBonds,NumRings,MolWt,Parsing Succesful?
0,CN1CC[C@@]2(C)c3cc(OC(=O)NCCCCCCCCCN4CCOCC4)cc...,CHEMBL220,34,4.207,6,1,57.28,11,4,472.674,True
1,Cc1ccc(C(=O)/C(=N/O)SCC[N+](C)(C)C)cc1.[Cl-],CHEMBL220,20,-0.59118,4,1,49.66,5,1,316.854,True
2,NC(=O)c1cc[n+](C/C=C/C[n+]2ccc(/C=N/O)cc2)cc1....,CHEMBL220,24,-5.567,3,2,83.44,6,2,458.154,True
3,O/N=C/c1cc[n+](CCC[n+]2ccccc2)cc1.[Br-].[Br-],CHEMBL220,20,-4.832,2,1,40.35,5,2,403.118,True
4,O/N=C/c1cc[n+](CCC[n+]2ccc3ccccc3c2)cc1.[Br-]....,CHEMBL220,24,-3.6788,2,1,40.35,5,3,453.178,True
...,...,...,...,...,...,...,...,...,...,...,...
20127,CC1=CC(=O)[C@@](C)(O)C(=O)/C1=C\Nc1ccc(Cc2cccc...,CHEMBL220,26,3.4223,4,2,66.4,4,3,347.414,True
20128,COc1cc2c(cc1OCCCCCC1CCSS1)C(=O)C(CC1CCN(Cc3ccc...,CHEMBL220,37,7.4454,6,0,38.77,12,5,539.807,True
20129,C#CCCCOc1c(CN2CCc3ccccc3C2)cc(-c2cc(=O)c3ccccc...,CHEMBL220,36,5.8191,5,0,51.91,8,5,479.576,True
20130,O=C(CCC1CCN(CC2CCCCC2)CC1)c1ccc(O)cc1,CHEMBL220,24,4.6474,3,1,40.54,6,3,329.484,True
20131,COc1c(C(=O)CCC2CCN(CC3CCCCC3)CC2)cc(F)c(N)c1Br,CHEMBL220,28,5.4342,4,1,55.56,7,3,455.412,True

In [15]:
from rdkit.Chem import rdFingerprintGenerator

mfpgen = rdFingerprintGenerator.GetMorganGenerator(radius=2, fpSize=256)

mol = Chem.MolFromSmiles(smiles_string)

fp = mfpgen.GetFingerprint(mol)
fp.ToList()[:10]
df['Fingerprints'] = fp
display(df)

,Smiles,Target ChEMBL ID,NumHeavyAtoms,LogP,HBA,HBD,TPSA,RotatableBonds,NumRings,MolWt,Parsing Succesful?,Fingerprints,Murcko Scaffolds,similarity
0,CN1CC[C@@]2(C)c3cc(OC(=O)NCCCCCCCCCN4CCOCC4)cc...,CHEMBL220,34,4.207,6,1,57.28,11,4,472.674,True,"[1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",O=C(NCCCCCCCCCN1CCOCC1)Oc1ccc2c(c1)C1CCN[C@@H]1N2,0.018868
1,Cc1ccc(C(=O)/C(=N/O)SCC[N+](C)(C)C)cc1.[Cl-],CHEMBL220,20,-0.59118,4,1,49.66,5,1,316.854,True,"[1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",c1ccccc1,0.030303
2,NC(=O)c1cc[n+](C/C=C/C[n+]2ccc(/C=N/O)cc2)cc1....,CHEMBL220,24,-5.567,3,2,83.44,6,2,458.154,True,"[1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",C(=C\C[n+]1ccccc1)/C[n+]1ccccc1,0.028571
3,O/N=C/c1cc[n+](CCC[n+]2ccccc2)cc1.[Br-].[Br-],CHEMBL220,20,-4.832,2,1,40.35,5,2,403.118,True,"[1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",c1cc[n+](CCC[n+]2ccccc2)cc1,0.107143
4,O/N=C/c1cc[n+](CCC[n+]2ccc3ccccc3c2)cc1.[Br-]....,CHEMBL220,24,-3.6788,2,1,40.35,5,3,453.178,True,"[1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",c1cc[n+](CCC[n+]2ccc3ccccc3c2)cc1,0.060606
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20127,CC1=CC(=O)[C@@](C)(O)C(=O)/C1=C\Nc1ccc(Cc2cccc...,CHEMBL220,26,3.4223,4,2,66.4,4,3,347.414,True,"[1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",O=C1C=C/C(=C/Nc2ccc(Cc3ccccc3)cc2)C(=O)C1,0.078947
20128,COc1cc2c(cc1OCCCCCC1CCSS1)C(=O)C(CC1CCN(Cc3ccc...,CHEMBL220,37,7.4454,6,0,38.77,12,5,539.807,True,"[1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",O=C1c2cc(OCCCCCC3CCSS3)ccc2CC1CC1CCN(Cc2ccccc2...,0.047619
20129,C#CCCCOc1c(CN2CCc3ccccc3C2)cc(-c2cc(=O)c3ccccc...,CHEMBL220,36,5.8191,5,0,51.91,8,5,479.576,True,"[1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",O=c1cc(-c2cccc(CN3CCc4ccccc4C3)c2)oc2ccccc12,0.033898
20130,O=C(CCC1CCN(CC2CCCCC2)CC1)c1ccc(O)cc1,CHEMBL220,24,4.6474,3,1,40.54,6,3,329.484,True,"[1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",O=C(CCC1CCN(CC2CCCCC2)CC1)c1ccccc1,0.054054
20131,COc1c(C(=O)CCC2CCN(CC3CCCCC3)CC2)cc(F)c(N)c1Br,CHEMBL220,28,5.4342,4,1,55.56,7,3,455.412,True,"[1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",O=C(CCC1CCN(CC2CCCCC2)CC1)c1ccccc1,0.039216

In [16]:
from rdkit.Chem.Scaffolds import MurckoScaffold

csv_data = pd.read_csv("File.csv")

def extract_single_scaffold(smiles_text):
    mol = Chem.MolFromSmiles(smiles_text)
    if mol is not None:
        scaffold_obj = MurckoScaffold.GetScaffoldForMol(mol)
        return Chem.MolToSmiles(scaffold_obj)
    return None

csv_data['scaffold_results'] = csv_data['Smiles'].apply(extract_single_scaffold)

df['Murcko Scaffolds'] = df['Smiles'].apply(extract_single_scaffold)

display(df)

,Smiles,Target ChEMBL ID,NumHeavyAtoms,LogP,HBA,HBD,TPSA,RotatableBonds,NumRings,MolWt,Parsing Succesful?,Fingerprints,Murcko Scaffolds,similarity
0,CN1CC[C@@]2(C)c3cc(OC(=O)NCCCCCCCCCN4CCOCC4)cc...,CHEMBL220,34,4.207,6,1,57.28,11,4,472.674,True,"[1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",O=C(NCCCCCCCCCN1CCOCC1)Oc1ccc2c(c1)C1CCN[C@@H]1N2,0.018868
1,Cc1ccc(C(=O)/C(=N/O)SCC[N+](C)(C)C)cc1.[Cl-],CHEMBL220,20,-0.59118,4,1,49.66,5,1,316.854,True,"[1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",c1ccccc1,0.030303
2,NC(=O)c1cc[n+](C/C=C/C[n+]2ccc(/C=N/O)cc2)cc1....,CHEMBL220,24,-5.567,3,2,83.44,6,2,458.154,True,"[1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",C(=C\C[n+]1ccccc1)/C[n+]1ccccc1,0.028571
3,O/N=C/c1cc[n+](CCC[n+]2ccccc2)cc1.[Br-].[Br-],CHEMBL220,20,-4.832,2,1,40.35,5,2,403.118,True,"[1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",c1cc[n+](CCC[n+]2ccccc2)cc1,0.107143
4,O/N=C/c1cc[n+](CCC[n+]2ccc3ccccc3c2)cc1.[Br-]....,CHEMBL220,24,-3.6788,2,1,40.35,5,3,453.178,True,"[1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",c1cc[n+](CCC[n+]2ccc3ccccc3c2)cc1,0.060606
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20127,CC1=CC(=O)[C@@](C)(O)C(=O)/C1=C\Nc1ccc(Cc2cccc...,CHEMBL220,26,3.4223,4,2,66.4,4,3,347.414,True,"[1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",O=C1C=C/C(=C/Nc2ccc(Cc3ccccc3)cc2)C(=O)C1,0.078947
20128,COc1cc2c(cc1OCCCCCC1CCSS1)C(=O)C(CC1CCN(Cc3ccc...,CHEMBL220,37,7.4454,6,0,38.77,12,5,539.807,True,"[1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",O=C1c2cc(OCCCCCC3CCSS3)ccc2CC1CC1CCN(Cc2ccccc2...,0.047619
20129,C#CCCCOc1c(CN2CCc3ccccc3C2)cc(-c2cc(=O)c3ccccc...,CHEMBL220,36,5.8191,5,0,51.91,8,5,479.576,True,"[1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",O=c1cc(-c2cccc(CN3CCc4ccccc4C3)c2)oc2ccccc12,0.033898
20130,O=C(CCC1CCN(CC2CCCCC2)CC1)c1ccc(O)cc1,CHEMBL220,24,4.6474,3,1,40.54,6,3,329.484,True,"[1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",O=C(CCC1CCN(CC2CCCCC2)CC1)c1ccccc1,0.054054
20131,COc1c(C(=O)CCC2CCN(CC3CCCCC3)CC2)cc(F)c(N)c1Br,CHEMBL220,28,5.4342,4,1,55.56,7,3,455.412,True,"[1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",O=C(CCC1CCN(CC2CCCCC2)CC1)c1ccccc1,0.039216

In [17]:
counts = df['Murcko Scaffolds'].value_counts()
top_scaffold = counts.idxmax()
top_10 = df['Murcko Scaffolds'].value_counts().head(10)

display(counts)
print(top_scaffold)
display(top_10)

Murcko Scaffolds
c1ccccc1                                              1085
                                                       474
c1ccc2nc3c(cc2c1)CCCC3                                 445
c1cc[n+](COC[n+]2ccccc2)cc1                            359
c1cc[nH+]cc1                                           357
                                                      ...
c1cnc2c(c1)CNCC2                                         1
O=C(/C=C/c1cccs1)c1ccccc1                                1
O=c1[nH]c(CCCCC2CCN(Cc3ccccc3)CC2)nc2c1cnn2C1CCCC1       1
C1=CC(c2ccccn2)N2N=C(c3ccccc3)SC2=N1                     1
O=C1/C(=C/c2ccc(OCCNCc3ccccc3)cc2)COc2ccccc21            1
Name: count, Length: 4777, dtype: int64

c1ccccc1

Murcko Scaffolds
c1ccccc1                                1085
                                         474
c1ccc2nc3c(cc2c1)CCCC3                   445
c1cc[n+](COC[n+]2ccccc2)cc1              359
c1cc[nH+]cc1                             357
c1cc[n+](CCC[n+]2ccccc2)cc1              323
O=C1c2ccccc2CC1CC1CCN(Cc2ccccc2)CC1      317
c1c[nH+]c[nH]1                           161
c1ccc(CN2CCN(c3ccccc3)CC2)cc1            157
C1=C[C@@]23CCNCc4cccc(c42)O[C@H]3CC1     148
Name: count, dtype: int64